# Generated by Django 2.1.2 on 2019-05-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryclient',
            name='by_air_route',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='client_price',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='follow_up_date_01',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='follow_up_date_02',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='follow_up_date_03',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='follow_up_date_04',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='follow_up_date_05',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='previous_tour',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='reason_of_cancel',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='special_requirment',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='update_01',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='update_02',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='update_03',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='update_04',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='update_05',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='visa_detail',
        ),
    ]
