# Generated by Django 2.1.2 on 2019-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190507_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryclient',
            name='by_air_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='client_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='follow_up_date_01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='follow_up_date_02',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='follow_up_date_03',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='follow_up_date_04',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='follow_up_date_05',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='previous_tour',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='reason_of_cancel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='special_requirment',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Confirm'), ('2', 'Cancel')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='update_01',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='update_02',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='update_03',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='update_04',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='update_05',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='visa_detail',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='2', max_length=1),
        ),
    ]
