# Generated by Django 2.2 on 2019-04-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood_group',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'AB+'), ('5', 'A-'), ('6', 'B-'), ('7', 'O-'), ('8', 'AB-')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='islamic',
            name='type',
            field=models.CharField(choices=[('1', 'Hazz'), ('2', 'Umrah')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('1', 'Normal Tour'), ('2', 'Oficial Tour'), ('3', 'Honeymoon')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='PackageTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', 'Normal Tour'), ('2', 'Oficial Tour'), ('3', 'Honeymoon')], default=1, max_length=1)),
                ('places', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=3)),
                ('members', models.IntegerField()),
                ('price', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
            ],
        ),
    ]
