# Generated by Django 2.2 on 2019-04-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190425_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageIslamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', 'Hajj'), ('2', 'Umrah')], default=1, max_length=1)),
                ('places', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=3)),
                ('members', models.IntegerField()),
                ('price', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
            ],
        ),
    ]
