# Generated by Django 2.1.2 on 2019-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190507_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='recieved_by',
            new_name='made_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_to',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_to_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_to_company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_to_phone',
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='being_the',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
