# Generated by Django 2.2 on 2019-04-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_packageislamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'AB+'), ('5', 'A-'), ('6', 'B-'), ('7', 'O-'), ('8', 'AB-')], default=1, max_length=1)),
                ('present_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('1', 'Normal Tour'), ('2', 'Oficial Tour'), ('3', 'Honeymoon'), ('4', 'Hajj'), ('5', 'Umrah'), ('6', 'Air Ticket'), ('7', 'Visa Processing')], default=1, max_length=1)),
                ('country_name', models.CharField(max_length=30)),
                ('places', models.CharField(max_length=200)),
                ('members', models.IntegerField()),
                ('airline', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='islamic',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='packageislamic',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.RemoveField(
            model_name='packageislamic',
            name='members',
        ),
        migrations.AddField(
            model_name='islamic',
            name='duration_nights',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='duration_nights',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetour',
            name='duration_nights',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_nights',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PackageVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('processing_time', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAirTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('departure_from', models.CharField(max_length=100)),
                ('departure_to', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
            ],
        ),
    ]
