# Generated by Django 2.2 on 2019-04-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190425_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageislamic',
            name='members',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
