# Generated by Django 2.1.2 on 2019-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190508_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_air_ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='package_air_ticket',
            field=models.ManyToManyField(blank=True, null=True, to='manager.PackageAirTicket'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_islamic',
        ),
        migrations.AddField(
            model_name='order',
            name='package_islamic',
            field=models.ManyToManyField(blank=True, null=True, to='manager.PackageIslamic'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_tour',
        ),
        migrations.AddField(
            model_name='order',
            name='package_tour',
            field=models.ManyToManyField(blank=True, null=True, to='manager.PackageTour'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_visa',
        ),
        migrations.AddField(
            model_name='order',
            name='package_visa',
            field=models.ManyToManyField(blank=True, null=True, to='manager.PackageVisa'),
        ),
    ]
