# Generated by Django 2.2 on 2019-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_packageislamic_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airticket',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RenameField(
            model_name='islamic',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RenameField(
            model_name='packageairticket',
            old_name='price',
            new_name='client_price',
        ),
        migrations.RenameField(
            model_name='packageislamic',
            old_name='price',
            new_name='client_price',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='price',
            new_name='client_price',
        ),
        migrations.RenameField(
            model_name='packagevisa',
            old_name='price',
            new_name='client_price',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RenameField(
            model_name='visa',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='price',
        ),
        migrations.AddField(
            model_name='airticket',
            name='client_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='client_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islamic',
            name='client_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageairticket',
            name='due_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageairticket',
            name='paid_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='due_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='paid_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetour',
            name='due_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetour',
            name='paid_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagevisa',
            name='due_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagevisa',
            name='paid_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='client_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='client_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='country_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='places',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Normal Tour'), ('2', 'Oficial Tour'), ('3', 'Honeymoon'), ('4', 'Hajj'), ('5', 'Umrah'), ('6', 'Air Ticket'), ('7', 'Visa Processing')], max_length=1, null=True),
        ),
    ]
