# Generated by Django 2.1.2 on 2019-05-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190509_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_air_ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='package_air_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageAirTicket'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_islamic',
        ),
        migrations.AddField(
            model_name='order',
            name='package_islamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageIslamic'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_tour',
        ),
        migrations.AddField(
            model_name='order',
            name='package_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageTour'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_visa',
        ),
        migrations.AddField(
            model_name='order',
            name='package_visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageVisa'),
        ),
    ]
