# Generated by Django 2.2 on 2019-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190426_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('change_password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('present_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('nid', models.IntegerField()),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('1', 'Married'), ('2', 'Unmarried')], default='2', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='airticket',
            old_name='departure_from',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='airticket',
            old_name='departure_to',
            new_name='departure',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='permanent_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='enquiryclient',
            old_name='permanent_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='enquiryclient',
            old_name='present_address',
            new_name='special_requirment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='enquiryclient',
            name='photo',
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='child',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('1', '5*'), ('2', 'O3*'), ('3', '2*')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='infant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryclient',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airticket',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='islamic',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='visa',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
