# Generated by Django 2.1.2 on 2019-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190509_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_air_ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='package_air_ticket',
            field=models.ManyToManyField(blank=True, null=True, to='manager.PackageAirTicket'),
        ),
    ]
