# Generated by Django 2.2 on 2019-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190427_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='change_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiryclient',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('1', '5*'), ('2', '3*'), ('3', '2*')], max_length=1, null=True),
        ),
    ]
