# Generated by Django 2.1.2 on 2019-05-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190509_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_air_ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='package_air_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageAirTicket'),
        ),
    ]
