# Generated by Django 2.1.2 on 2019-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190509_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryclient',
            name='do_register',
            field=models.BooleanField(default=False),
        ),
    ]
