# Generated by Django 2.1.2 on 2019-05-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_enquiryclient_do_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageislamic',
            name='special_requirment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packagetour',
            name='special_requirment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
