# Generated by Django 2.2 on 2019-04-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190427_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageairticket',
            old_name='departure_from',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='packageairticket',
            old_name='departure_to',
            new_name='departure',
        ),
    ]
