# Generated by Django 2.2 on 2019-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190427_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageairticket',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='packagevisa',
            name='actual_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
