# Generated by Django 2.2 on 2019-06-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190510_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('catagory_name', models.CharField(max_length=30)),
                ('border_color', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Employee')),
            ],
        ),
    ]
