# Generated by Django 2.2 on 2019-06-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_marketing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketing',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
