# Generated by Django 2.2 on 2019-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190428_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='child',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('1', '5*'), ('2', '3*'), ('3', '2*')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='infant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageislamic',
            name='special_requirment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetour',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='child',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('1', '5*'), ('2', '3*'), ('3', '2*')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='infant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='special_requirment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
