# Generated by Django 2.2 on 2019-06-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190630_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=300)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Marketing')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Employee')),
            ],
        ),
    ]
