# Generated by Django 2.2 on 2019-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20190428_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageairticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
