# Generated by Django 2.2 on 2019-06-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_marketingemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketingEmails',
            new_name='MarketingEmail',
        ),
    ]
