# Generated by Django 2.2 on 2019-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20190630_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='border_color',
        ),
    ]
