# Generated by Django 2.2 on 2019-04-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20190429_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='package_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageTour'),
        ),
    ]
