# Generated by Django 2.2 on 2019-04-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20190429_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='package_air_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageAirTicket'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='package_islamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageIslamic'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='package_visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageVisa'),
        ),
    ]
