# Generated by Django 2.2 on 2019-04-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20190429_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('1', 'Cash'), ('2', 'Cheque'), ('3', 'DD'), ('4', 'TT')], default='1', max_length=1)),
                ('cheque_number', models.CharField(blank=True, max_length=30)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('cheque_date', models.CharField(blank=True, max_length=30)),
                ('booking_id', models.CharField(blank=True, max_length=30)),
                ('actual_price', models.IntegerField()),
                ('total_ammount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('payable_ammount', models.IntegerField()),
                ('received_ammount', models.IntegerField()),
                ('due_ammount', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Employee')),
                ('package_air_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageAirTicket')),
                ('package_islamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageIslamic')),
                ('package_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageTour')),
                ('package_visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.PackageVisa')),
            ],
        ),
    ]
