# Generated by Django 2.2 on 2019-04-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageairticket',
            name='due_price',
        ),
        migrations.RemoveField(
            model_name='packageairticket',
            name='paid_price',
        ),
        migrations.RemoveField(
            model_name='packageislamic',
            name='due_price',
        ),
        migrations.RemoveField(
            model_name='packageislamic',
            name='paid_price',
        ),
        migrations.RemoveField(
            model_name='packagetour',
            name='due_price',
        ),
        migrations.RemoveField(
            model_name='packagetour',
            name='paid_price',
        ),
        migrations.RemoveField(
            model_name='packagevisa',
            name='due_price',
        ),
        migrations.RemoveField(
            model_name='packagevisa',
            name='paid_price',
        ),
    ]
