# Generated by Django 2.2 on 2019-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20190430_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_by', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('by', models.CharField(choices=[('1', 'Cash'), ('2', 'Cheque')], default='1', max_length=1)),
                ('being_the', models.CharField(max_length=200)),
                ('description_01', models.CharField(blank=True, max_length=100)),
                ('cost_01', models.IntegerField(default=0)),
                ('description_02', models.CharField(blank=True, max_length=100)),
                ('cost_02', models.IntegerField(default=0)),
                ('description_03', models.CharField(blank=True, max_length=100)),
                ('cost_03', models.IntegerField(default=0)),
                ('description_04', models.CharField(blank=True, max_length=100)),
                ('cost_04', models.IntegerField(default=0)),
                ('description_05', models.CharField(blank=True, max_length=100)),
                ('cost_05', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
