# Generated by Django 2.2 on 2019-04-30 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
