# Generated by Django 2.2 on 2019-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_order_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_ammount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
