# Generated by Django 2.2 on 2019-05-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_order_unit_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_ammount',
        ),
    ]
