# Generated by Django 2.2 on 2019-05-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_remove_order_unit_ammount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Employee')),
            ],
        ),
    ]
